# Change these first
owner: Space-Turtle0 # Your GitHub username
repo: PortalBOT-Hosting # Your GitHub repository name

# Add your sites here
sites:
  - name: STABLE
    url: $PORTALBOT_STABLE
    icon: https://media.discordapp.net/attachments/796137662317854760/796137738583146556/Nether_Portal_Avatargreen.png
    
  - name: BETA
    url: $PORTALBOT_BETA
    icon: https://cdn.discordapp.com/attachments/796137662317854760/796137745046437908/Portal_Design.png

  - name: TestInstance
    url: https://thissitedoesnotexist.com/
    
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  baseUrl: /PortalBOT-Hosting
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is recording PortalBOT's uptime!"
  introMessage: Tracking PortalBOT Stable and PortalBOT Beta!
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
